
title: Antonio Gonzalez Portfolio
email: antonio@gonzalezh.com
description: > # this means to ignore newlines until "baseurl:"
  Personal Portfolio
baseurl: "" # subpath
url: "https://gonzalezh.com" #
twitter_username: #
github_username:  #

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
